export const UNIVERSITIES = [
  'Adeleke University',
  'Ahmadu Bello University',
  'Babcock University',
  'Covenant University',
  'Federal University of Technology, Akure',
  'Federal University of Technology, Minna',
  'Lagos State University',
  'Obafemi Awolowo University',
  'University of Benin',
  'University of Ibadan',
  'University of Ilorin',
  'University of Jos',
  'University of Lagos',
  'University of Nigeria, Nsukka',
  'University of Port Harcourt',
].sort();

export const COURSES = [
  'Accounting', 'Actuarial Science', 'Adult Education', 'Agricultural Economics',
  'Agricultural Engineering', 'Agricultural Extension', 'Agriculture', 'Agronomy',
  'Anatomy', 'Animal Science', 'Applied Biology', 'Applied Chemistry',
  'Applied Geophysics', 'Arabic Studies', 'Archaeology', 'Architecture',
  'Artificial Intelligence',
  'Banking and Finance', 'Biochemistry', 'Biology', 'Biomedical Engineering',
  'Botany', 'Building Technology', 'Business Administration', 'Business Education',
  'Chemical Engineering', 'Chemistry', 'Christian Religious Studies',
  'Civil Engineering', 'Computer Engineering', 'Computer Science',
  'Criminology and Security Studies', 'Crop Science',
  'Dentistry', 'Drama / Theatre Arts',
  'Early Childhood Education', 'Economics', 'Education and Biology',
  'Education and Chemistry', 'Education and Computer Science',
  'Education and English', 'Education and Mathematics', 'Education and Physics',
  'Educational Administration', 'Electrical Engineering', 'Electronics Engineering',
  'English and Literary Studies', 'Entrepreneurship', 'Environmental Management',
  'Estate Management',
  'Fisheries', 'Food Science and Technology', 'Forestry', 'French',
  'Geography', 'Geology', 'Geomatics', 'Guidance and Counselling',
  'Hausa', 'Health Education', 'History', 'Home Economics', 'Human Anatomy',
  'Human Kinetics', 'Human Nutrition',
  'Igbo', 'Industrial Chemistry', 'Industrial Design', 'Industrial Mathematics',
  'Industrial Physics', 'Information Science', 'Information Technology',
  'Insurance', 'International Relations', 'Islamic Studies',
  'Journalism',
  'Law', 'Library and Information Science', 'Linguistics',
  'Marine Engineering', 'Marketing', 'Mass Communication', 'Mathematics',
  'Mechanical Engineering', 'Mechatronics Engineering', 'Medical Laboratory Science',
  'Medicine and Surgery', 'Metallurgical Engineering', 'Microbiology',
  'Mining Engineering', 'Music',
  'Nursing Science', 'Nutrition and Dietetics',
  'Oceanography', 'Optometry',
  'Peace and Conflict Studies', 'Petroleum Engineering', 'Pharmacology',
  'Pharmacy', 'Philosophy', 'Physics', 'Physiology', 'Physiotherapy',
  'Plant Science', 'Political Science', 'Psychology', 'Public Administration',
  'Public Health',
  'Quantity Surveying',
  'Radiography', 'Religious Studies',
  'Sociology', 'Software Engineering', 'Soil Science', 'Special Education',
  'Statistics', 'Surveying and Geoinformatics',
  'Taxation', 'Theatre Arts', 'Theology', 'Tourism Studies',
  'Urban and Regional Planning',
  'Veterinary Medicine',
  'Yoruba',
].sort((a, b) => a.localeCompare(b));

export const YEAR_OF_STUDY_OPTIONS = [
  { label: '100 Level', value: '100' },
  { label: '200 Level', value: '200' },
  { label: '300 Level', value: '300' },
  { label: '400 Level', value: '400' },
  { label: '500 Level', value: '500' },
];
